board/iotdk/drivers/pmwifi/pmwifi.c, board/iotdk/drivers/pmwifi/pmwifi.h, board/iotdk/iotdk.h
support mrf24g pmod wifi module;
tested with example/freertos/net/httpserver example
=> Drivers: add pmwifi drivers to iotdevkit

.travis.yml, .travis/build.py, .travis/script.sh
- Show build status of each job on github
Add a variable EMBARC_BOT on travis ci , it's value should be "github_username:github_token "
=> travis: Split sub jobs and show status in github

.ci/before_install.sh, .ci/build.py
- when find board version, it ill check if there is a folder named "configs" in "board/boardname/", if yes, it will find versions in "board/boardname/configs ". it will find version  in "board/boardname/",.
- the tcf files should be named after core
=> travis: Adjust the strategy to find bd_ver and core

device/peripheral/ble/rn4020/rn4020.c, device/peripheral/ble/rn4020/rn4020.h, example/baremetal/ble_rn4020/README.rst, example/baremetal/ble_rn4020/main.c, middleware/common/ez_sio/ez_sio.h
modify rn4020 driver and example: use ez_sio module
=> modify rn4020 driver and example: use ez_sio module

.ci/before_install.sh, .ci/build.py, .ci/deploy_doc.sh, .gitlab-ci.yml, .travis.yml
- send the result of  `make linkcheck`, [testcase](https://github.com/wangnuannuan/embarc_osp/pull/1) .
- send the result of compilation .
- in `.gitlabci.yaml`, delete delete variable CUR_CORE.
=> travis: when pull requests, send the wrong result as a comment to github

board/iotdk/common/iotdk_init.c, device/peripheral/flash/w25qxx/spi_flash_w25qxx.c, device/peripheral/flash/w25qxx/spi_flash_w25qxx.h, example/baremetal/test/iotdk/spiflash_test/main.c, example/freertos/esp8266_wifi/FreeRTOSConfig.h, example/freertos/esp8266_wifi/at_parser.c, example/freertos/esp8266_wifi/at_parser.h, example/freertos/esp8266_wifi/esp8266.c, example/freertos/esp8266_wifi/esp8266.h, example/freertos/esp8266_wifi/main.c, example/freertos/esp8266_wifi/makefile
device: flash: bug fixes in spi_flash_w25qxx driver
=> device: flash: bug fixes in spi_flash_w25qxx driver

.ci/before_install.sh, .ci/build.py, .ci/deploy_doc.sh, .gitlab-ci.yml, .travis.yml
- Sphinx documentation link check result will be commented in pull request
- Each build result will be commented in pull request as table
=> ci: Enable travis build result comment in pull request

board/iotdk/drivers/smic/smic_bootspi/smic_bootspi.c, board/iotdk/drivers/smic/smic_bootspi/smic_bootspi.h, board/iotdk/iotdk.h, board/iotdk/iotdk.mk
board: iotdk: add smic_bootspi driver
=> board: iotdk: add smic_bootspi driver

example/baremetal/bootloader/README.rst, example/baremetal/bootloader/appl_mem_config.h, example/baremetal/bootloader/main.c, example/baremetal/bootloader/makefile, middleware/ntshell/cmds/cmds_fs/cmd_cls.c, middleware/ntshell/cmds/cmds_fs/cmd_eflash.c, middleware/ntshell/cmds/cmds_fs/cmd_flash.c, middleware/ntshell/cmds/cmds_fs/cmds_fs.c, middleware/ntshell/cmds/cmds_fs/cmds_fs_cfg.h
ntshell: add cls and eflash command support
bootloader: add startup from iotdk eflash support
=> add ntshell cls and eflash command and bootloader startup from iotdk eflash support 

example/freertos/iot/coap/coap_server/FreeRTOSConfig.h, example/freertos/iot/coap/coap_server/main.c, example/freertos/iot/coap/coap_server/makefile, example/freertos/iot/lwm2m/lwm2m_client/makefile, example/freertos/iot/lwm2m/lwm2m_server/makefile
example: coap_server: add support for iotdk
=> example: coap_server: add support for iotdk

doc/documents/lib/secureshield.rst
Signed-off-by: Yiping Peng <yibingp@synopsys.com>
- update the document of library secureshield
=> doc: update the doc of library secureshield

device/ip/designware/spi/dw_spi.c, device/ip/designware/spi/dw_spi.h, device/ip/ip_hal/inc/dev_spi.h, device/peripheral/flash/fl256s/spi_flash_fl256s.c, device/peripheral/flash/fl256s/spi_flash_fl256s.h
device: ip: designware: spi: add quad read mode
device: flash: fl256s: add quad read function
=> quad spi read fucntion

.ci/build.py, .travis.yml
1.  delete unnecessary build parameters
2.  when build failed , it will send email
=> travis: modify code according to embarc cli

doc/documents/board/emsdp.rst, doc/documents/getting_started/peripheral_preparation.rst
Modify package info
Use em11d as example in document
fix document url
Signed-off-by: Yuguo Zou <yuguo.zou@synopsys.com>
- Summarize the main changes or features of your pull request.
- Describe the development status of your pull request.
- List all the related issues of your pull request.
- [] Todo list 1
- [] Todo list 2
Describe about how to test or reproduce the new features or bugs fixed of your pull request.
=> emsdp: modify document

board/iotdk/drivers/smic/smic_eflash/smic_eflash.c, board/iotdk/drivers/smic/smic_eflash/smic_eflash.h
=> board: iotdk: smic_eflash: bugs fix and code optimizes

.ci/before_install.sh, .ci/script.sh, doc/documents/conf.py, doc/documents/contribute/CONTRIBUTING.md, example/baremetal/openthread/cli/OT_CLI.md, middleware/mbedtls/0001-Add-embARC-FreeRTOS-LwIP-support-to-mbedtls.patch, middleware/mbedtls/0002-update-the-copyright-and-add-the-support-of-DW-timer.patch, scripts/patch.py, scripts/patch.rst, scripts/requirements.txt
- add python script to apply patch
- add repo link and repo commit to patch , 
```
git format-patch xxx --add-header="repo_link:https://github.com/ARMmbed/mbedtls.git repo_commit:mbedtls-2.4.1"
```
- modify link format in markdown.
=> tool: add python script to apply patch

doc/documents/board/emsk.rst, doc/documents/board/iotdk.rst
bug fixes and add PMOD pins definition for EMSK
=> doc: board: bug fixes and add PMOD pins definition for EMSK

.ci/build.py, .ci/toolchain.py, .travis.yml, device/ip/ip_hal/inc/dev_gpio.h, doc/documents/board/emsk.rst, doc/documents/changelog/release_2016.05.rst, doc/documents/conf.py, doc/documents/contribute/CONTRIBUTING.md, doc/documents/device/gpio.rst, doc/documents/getting_started/hardware_requirement.rst, doc/documents/getting_started/makefile_manual.rst, doc/documents/getting_started/peripheral_preparation.rst, doc/documents/getting_started/software_requirement.rst, doc/documents/license/license.rst, example/baremetal/ble_hm1x/README.rst, example/baremetal/ble_rn4020/README.rst, example/baremetal/openthread/cli/OT_CLI.md
Signed-off-by: Jingru <jingru@synopsys.com>
=> doc: modify punctuation and spelling

example/baremetal/arc_feature/cache/main.c, example/baremetal/arc_feature/timer_interrupt/main.c, example/baremetal/arc_feature/udma/main.c
The key words are useful for automation to detect if the example is passed.
Now use `Test Done` as key words
Signed-off-by: Jingru Wang <jingru@synopsys.com>
=> example: add key words to arc_feature examples

scripts/test.py
Signed-off-by: Jingru Wang <jingru@synopsys.com>
=> scripts: mark result as skipped when unsupported secureshield

doc/documents/contribute/CONTRIBUTING.rst, doc/documents/example/example.rst, doc/documents/getting_started/peripheral_preparation.rst, doc/documents/license/license.rst
use 'make linkcheck' to check urls
Signed-off-by: Jingru Wang <jingru@synopsys.com>
=> doc: check and fix urls

.github/workflows/doc-build.yml, doc/documents/contribute/CONTRIBUTING.rst, doc/documents/example/example.rst, doc/documents/getting_started/peripheral_preparation.rst, doc/documents/license/license.rst, scripts/requirements_doc.txt
Use GitHub Action to build document and push the generated document to gh-pages branch
=> add action workflow for osp

.github/workflows/doc-build.yml
Signed-off-by: Jingru Wang <jingru@synopsys.com>
=> action: only trigger action when push to master
